### Get All Projects
GET http://localhost:8080/api/projects
Accept: application/json

### Get Project by ID
GET http://localhost:8080/api/projects/1
Accept: application/json

### Create New Project
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": "New Project Name",
  "description": "Description for the new project.",
  "ownerId": 1
}

### Update Project by ID
PUT http://localhost:8080/api/projects/1
Content-Type: application/json

{
  "name": "Updated Project Name"
}

### Delete Project by ID
DELETE http://localhost:8080/api/projects/1
